ui: tape
browserify:
  - transform: babelify
browsers:
  - name: chrome
    version: -1..latest
  - name: firefox
    version: -1..latest
  - name: safari
    version: -1..latest
  - name: opera
    version: -1..latest
  - name: ie
    version: -1..latest
  - name: iphone
    version: -1..latest
  - name: ipad
    version: -1..latest
  - name: android
    version: -1..latest